defaultPlacement: end
enableVersioning: true
entryTypes:
  - 9af4493f-1473-46c6-8dc2-d79d5503d1b7 # Rich Text
handle: about
maxAuthors: 1
name: About
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  d9d1ae21-b5ed-442d-bc28-0e3aa8b8c39b: # TrailQuest
    enabledByDefault: true
    hasUrls: true
    template: about/_entry
    uriFormat: about
type: single
