defaultPlacement: end
enableVersioning: true
entryTypes:
  - de9912bf-cf02-4036-9107-e326c86f86bf # Adventures
handle: adventures
maxAuthors: 1
name: Adventures
previewTargets:
  0:
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
  2:
    __assoc__:
      -
        - label
        - 'Listing page'
      -
        - urlFormat
        - /adventures
      -
        - refresh
        - '1'
  3:
    __assoc__:
      -
        - label
        - Homepage
      -
        - urlFormat
        - /
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  d9d1ae21-b5ed-442d-bc28-0e3aa8b8c39b: # TrailQuest
    enabledByDefault: true
    hasUrls: true
    template: adventures/_entry.twig
    uriFormat: 'adventures/{slug}'
type: channel
