defaultPlacement: end
enableVersioning: true
entryTypes:
  - c3a92b48-89a3-4e38-9bba-392cdfbf35bf # Homepage
handle: homepage
maxAuthors: 1
name: Homepage
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  d9d1ae21-b5ed-442d-bc28-0e3aa8b8c39b: # TrailQuest
    enabledByDefault: true
    hasUrls: true
    template: index.twig
    uriFormat: __home__
type: single
